name = "Jorm"
uuid = "8ed0ba2e-9b92-4829-8f37-c861db1f7b18"
authors = ["Jcharis <jcharistech@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
SQLite = "1"
julia = "1.10.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
